FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y piper && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app


EXPOSE ${TTS_PORT}

CMD ["python", "-m", "app.main"]
